### PR TITLE
Added ability to configure table parameters as default name and table prefix

### PR DESCRIPTION
**Pull request by VojtechBartos**
Extended configuration with new attribute `table`, which allows to set default table name and prefix for each parsed key table name

```yml
table:
  defaultName: default # default table name defaults to default
  prefix: ds_ # table prefix defaults to empty string, so no prefix
```

Both new addition defaults to current master settings so default name is `default` and no table prefix

### CODE REVIEW

**Comment by VojtechBartos** [comment]
@yasserf @WolframHempel any chance you could take a look into it?

**Comment by yasserf** [comment]
LGTM, thank you! Did you sign the CLA by any chance? 

https://deepstream.typeform.com/to/PwwNd5

**Comment by VojtechBartos** [comment]
@yasserf done, signed.

**Comment by yasserf** [comment]
Epic, thanks!

**Comment by yasserf** [comment]
@jshrt want to arrange a release?

**Pull request merged**
