### PR TITLE
[task] version 3.0.0

### PR DESCRIPTION
**Pull request by jaime-ez**
Bump version, update changelog and clarify the defaultTable option.

it's not possible to do tags in PRs :(

### CODE REVIEW

**Comment by yasserf** [comment]
FYI, if we release this the next deepstream release will break for postgres users. Given the project is in maintenance mode I don't want to introduce breaking changes in there. Can we change the docker file in deepstream root to install v2 of this adaptor?

**Comment by yasserf** [comment]
FYI, if we release this the next deepstream release will break for postgres users. Given the project is in maintenance mode I don't want to introduce breaking changes in there. Can we change the docker file in deepstream root to install v2 of this adaptor?

**Comment by jaime-ez** [comment]
Yes that seems right to me. I'll try to update the website in the next days
and put a note that warns about this.

**Comment by yasserf** [comment]
Thanks again for the work @jaime-ez

**Comment by yasserf** [comment]
btw @jaime-ez, happy to add you into the org so that u can do tags and such directly. Let me know if your interested

**Comment by jaime-ez** [comment]
@yasserf I made another push to include a std logger for use in standalone mode.

> Can we change the docker file in deepstream root to install v2 of this adaptor?

We could use a different branch maybe for version 3? So users who want to use it install it with the corresponding tag identifier, and the docker file is kept as it is,  avoiding having to revert it back in a future scenario...

And sure I'll be glad to be part of the org :+1:

**Comment by yasserf** [comment]
Welcome to the org! 🦸

**Pull request merged**
